server:
  port: 8083
  servlet:
    context-path: /stock-service
spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://localhost:3306/stock_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off

client:
  feign:
    payment-service:
      path: http://localhost:8078/payment
      userOrderedProduct: /product/ordered

    microServiceRegister-service:
      path: http://localhost:8090/registerservice
      ready: /ready
      stopped: /stopped

    user-service:
      path: http://localhost:8082/user
      extractRoleFromToken: /extract/role
      extractSellerNameFromToken: /extract/seller-name

    token-service:
      path: http://localhost:8079/token
      extractUsername: /extract/username

app:
  client:

#app:
#  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
#  jwtCryptoSecret : sBnlg0BGosgPMQju
#logging:
#  level:
#    org.springframework: DEBUG
